// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://pzdnpksdcndpmmgtkbey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZG5wa3NkY25kcG1tZ3RrYmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDI2NzYsImV4cCI6MjA3NDQ3ODY3Nn0.A11TRQjF7Rgr9hcwRxvF_sTfSXELaNnx2e7cNZ5zAEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});